import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

import type { Metadata } from "next";
import "./globals.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import { theme } from "@/theme";

import SessionProvider from "@/components/SessionProvider";
import { EdgeStoreProvider } from "@/libs/edgestore";

import { getServerSession } from "next-auth";
import { authOption } from "@/libs/authOption";

export const metadata: Metadata = {
  title: "E-book store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOption);
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <SessionProvider session={session}>
          <EdgeStoreProvider>
            <MantineProvider theme={theme}>
              <Notifications />
              <main className="bg-light">
                {children}
              </main>
            </MantineProvider>
          </EdgeStoreProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
